const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const weather=require('../assets/jr-weather-fields-v37.js');
const ball=require('../assets/jr-ball-model-v37.js');
const now=Date.now();
assert.equal(ball.panels.length,32);
assert.equal(ball.panels.filter(p=>p.dark&&p.points.length===5).length,12);
assert.equal(ball.panels.filter(p=>!p.dark&&p.points.length===6).length,20);
for(const p of ball.panels)for(const v of p.points)assert(Math.abs(Math.hypot(...v)-1)<1e-10);
assert.equal(weather.fieldFor('C. de Gasca').id,'cerrito');
assert.equal(weather.fieldFor('S. Juan de la Cruz').id,'san-juan');
assert.equal(weather.fieldFor('1').id,'sur-1');
assert.equal(weather.fieldFor('campo inventado'),undefined);
assert.equal(weather.readReport('sur-1',{},now).status,'unknown');
assert.equal(weather.cleanReport({status:'fit',reviewedAt:new Date(now+86400000)},now),null);
const old={status:'fit',reviewedAt:new Date(now-13*3600000).toISOString()};
assert.equal(weather.readReport('sur-1',{'sur-1':old},now).status,'unknown');
assert.equal(weather.readReport('sur-1',{'sur-1':old},now).stale,true);
const fresh={status:'heavy',reviewedAt:new Date(now-1000).toISOString()};
assert.equal(weather.readReport('sur-1',{'sur-1':fresh},now).status,'heavy');
assert.equal(weather.risk('unfit',{prob:0}).level,'red');
assert.equal(weather.risk('fit',{prob:90,storm:false,gust:20}).level,'yellow');
assert.equal(weather.risk('unknown',{prob:0}).level,'yellow');
assert.equal(weather.risk('fit',{prob:0,storm:true}).level,'orange');
assert.equal(weather.summarize([]).prob,null);
assert.equal(weather.summarize([]).mm,null);
const data={hourly:{time:[100,3700,7300],precipitation_probability:[0,null,88],precipitation:[0,null,3.2],wind_speed_10m:[0,10,20],wind_gusts_10m:[0,20,35],weather_code:[0,1,95]}};
const hours=weather.weatherHours(data,100000,7300000);
assert.equal(hours.length,2);assert.equal(hours[0].prob,0);assert.equal(hours[1].prob,null);
assert.equal(weather.summarize(hours).mm,null);
assert.equal(weather.weatherHours(data,99999999,199999999).length,0);
assert.equal(weather.matchId('Veteranos 35+',{home:'C. de Gasca',away:'Pozos FC'}),'veteranos-35-__c-de-gasca__pozos-fc');
assert.equal(weather.cleanMatch({status:'suspended',kickoff:'bad',updatedAt:new Date().toISOString()}),null);
assert.equal(weather.cleanMatch({status:'suspended',kickoff:null,updatedAt:new Date().toISOString()}).status,'suspended');
assert.equal(weather.cleanMatch({status:'__proto__',updatedAt:new Date().toISOString()}),null);
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
for(const file of ['jr-ball-model-v37.js','jr-weather-fields-v37.js','jr-experience-v37.js','jr-v37.css'])assert.equal(html.split(file).length-1,1);
assert(html.indexOf('jr-ball-model-v37.js')<html.indexOf('football-scene.js'));
const files=Array.from(html.matchAll(/(?:src|href)="\.\/([^"?#]+)(?:[?#][^"]*)?"/g));
for(const [,file]of files)assert(fs.existsSync(path.join(__dirname,'..',file)),`Missing local asset: ${file}`);
console.log('V37: geometry, venue aliases, stale reports, weather nulls, match validation and local asset links passed.');

const calendar=require('../assets/jr-calendar-v37.js');
const schedule=[{id:'example',home:'Uno',away:'Dos',category:'Prueba',field:'Campo; 1',status:'scheduled',kickoff:'2026-09-12T16:00:00-06:00',note:'Revisión\r\nBEGIN:VEVENT'}];
const ics=calendar.buildICS(schedule,Date.parse('2026-09-12T10:00Z'));
assert(ics.includes('DTSTART:20260912T220000Z'));
assert(ics.includes('LOCATION:Campo\\; 1'));
assert.equal(ics.split('\r\nBEGIN:VEVENT').length-1,1);
assert(!calendar.buildICS([{...schedule[0],status:'suspended'}]).includes('BEGIN:VEVENT'));
assert(!calendar.buildICS([{...schedule[0],kickoff:null}]).includes('BEGIN:VEVENT'));
for(const line of calendar.fold('SUMMARY:'+ 'é'.repeat(100)).split('\r\n'))assert(Buffer.byteLength(line,'utf8')<=73);
console.log('V37: calendar timezone, state filtering, text escaping and UTF-8 folding passed.');
